apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replica
  namespace: my-namespace
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: api
          image: registry.cluster.wik.cloud/public/echo
          ports:
            - containerPort: 80
